INSERT INTO roles (id, name, slug) VALUES
(1, 'Super Admin', 'super_admin'),
(2, 'Admin', 'admin');

INSERT INTO permissions (name, slug) VALUES
('Manage content', 'manage_content'),
('Manage leads', 'manage_leads'),
('Manage users', 'manage_users');

INSERT INTO role_permissions (role_id, permission_id) VALUES (1,1),(1,2),(1,3),(2,1),(2,2);

INSERT INTO users (role_id, full_name, email, password_hash, status, created_at) VALUES
(1, 'Site Administrator', 'admin@four-seasons.local', '$2y$12$Jxx5GfOIYhs0VnHe6sGqjOHYyQAvuivn3J7Vcj/ju50a0o7YV.Nqi', 1, NOW());

INSERT INTO settings (setting_key, setting_value, updated_at) VALUES
('site_name', 'Four Seasons Canada', NOW()),
('tagline', 'Immigration & Study Services', NOW()),
('email', 'info@four-seasons.ca', NOW()),
('phone', '+1 647 761 3002', NOW()),
('address', '90 Burnhamthorpe Rd West, 14th Flr, Sussex Centre, Mississauga, Ontario L5B 3C3', NOW()),
('city', 'Mississauga, Ontario', NOW()),
('hours', 'Monday–Friday 9:00am–6:00pm', NOW()),
('facebook', '#', NOW()),
('instagram', '#', NOW()),
('linkedin', '#', NOW()),
('seo_title', 'Four Seasons Canada | Immigration and International Education', NOW()),
('seo_description', 'Independent consultancy for Canadian study permits, immigration pathways, family sponsorship, and visitor services.', NOW()),
('og_image', 'assets/images/og-placeholder.svg', NOW()),
('footer_about', 'Four Seasons Canada helps individuals and families plan Canadian education and immigration journeys with clear guidance and professional support.', NOW()),
('copyright', 'Four Seasons Canada. All rights reserved.', NOW());

INSERT INTO menu_items (id, title, slug, url, parent_id, sort_order, status) VALUES
(1, 'Education', 'education', '/education', 0, 1, 1),
(2, 'Immigration', 'immigration', '/immigration', 0, 2, 1),
(3, 'Sponsorship', 'sponsorship', '/sponsorship', 0, 3, 1),
(4, 'Visit', 'visit', '/visit', 0, 4, 1),
(5, 'Others', 'others', '/others', 0, 5, 1),
(6, 'About Us', 'about-us', '/about/who-we-are', 0, 6, 1),
(10, 'Study Permit', 'study-permit', '/education/study-permit', 1, 1, 1),
(11, 'Post Graduation Work Permit', 'post-graduation-work-permit', '/education/post-graduation-work-permit', 1, 2, 1),
(12, 'Spouse Open Work Permit', 'spouse-open-work-permit', '/education/spouse-open-work-permit', 1, 3, 1),
(13, 'Status Extension', 'status-extension', '/education/status-extension', 1, 4, 1),
(20, 'Express Entry', 'express-entry', '/immigration/express-entry', 2, 1, 1),
(21, 'Canadian Experience Class', 'canadian-experience-class', '/immigration/canadian-experience-class', 2, 2, 1),
(22, 'Federal Skilled Worker', 'federal-skilled-worker', '/immigration/federal-skilled-worker', 2, 3, 1),
(23, 'Provincial Nominee Programs', 'provincial-nominee-programs', '/immigration/provincial-nominee-programs', 2, 4, 1),
(24, 'Pilot Programs', 'pilot-programs', '/immigration/pilot-programs', 2, 5, 1),
(30, 'Family Sponsorship', 'family-sponsorship', '/sponsorship/family-sponsorship', 3, 1, 1),
(31, 'Parents and Grandparents', 'parents-and-grandparents', '/sponsorship/parents-and-grandparents', 3, 2, 1),
(32, 'Other Relatives', 'other-relatives', '/sponsorship/other-relatives', 3, 3, 1),
(40, 'Family or Leisure', 'family-or-leisure', '/visit/family-or-leisure', 4, 1, 1),
(41, 'Super Visa', 'super-visa', '/visit/super-visa', 4, 2, 1),
(42, 'Business or Exploratory', 'business-or-exploratory', '/visit/business-or-exploratory', 4, 3, 1),
(50, 'Citizenship', 'citizenship', '/others/citizenship', 5, 1, 1),
(51, 'PR Renewal', 'pr-renewal', '/others/pr-renewal', 5, 2, 1),
(52, 'Status Restoration', 'status-restoration', '/others/status-restoration', 5, 3, 1),
(53, 'LMIA', 'lmia', '/others/lmia', 5, 4, 1),
(54, 'Work Permit', 'work-permit', '/others/work-permit', 5, 5, 1),
(55, 'Visa Refusals', 'visa-refusals', '/others/visa-refusals', 5, 6, 1),
(60, 'Who We Are', 'who-we-are', '/about/who-we-are', 6, 1, 1),
(61, 'What We Do', 'what-we-do', '/about/what-we-do', 6, 2, 1),
(62, 'Where We Are', 'where-we-are', '/about/where-we-are', 6, 3, 1);

INSERT INTO service_categories (id, title, slug, intro, sort_order, status, seo_title, seo_description) VALUES
(1, 'Education', 'education', 'Support for study permits, school placement, and post-study work options in Canada.', 1, 1, 'Education Services | Four Seasons Canada', 'Study permits, admissions guidance, and post-graduation options for international students.'),
(2, 'Immigration', 'immigration', 'Pathways toward Canadian permanent residence and skilled immigration.', 2, 1, 'Immigration Services | Four Seasons Canada', 'Express Entry, PNP, skilled worker, and related immigration consulting.'),
(3, 'Sponsorship', 'sponsorship', 'Family reunification options for eligible sponsors in Canada.', 3, 1, 'Family Sponsorship | Four Seasons Canada', 'Family, parent, and relative sponsorship guidance.'),
(4, 'Visit', 'visit', 'Temporary resident options for family visits, Super Visa, and business travel.', 4, 1, 'Visit Canada | Four Seasons Canada', 'Visitor visa, Super Visa, and business visitor guidance.'),
(5, 'Others', 'others', 'Additional immigration-related services including citizenship and status solutions.', 5, 1, 'Other Immigration Services | Four Seasons Canada', 'Citizenship, PR renewal, LMIA, work permits, and refusal support.'),
(6, 'Additional', 'additional', 'Extra inquiry options that are not listed as primary navigation children.', 6, 0, 'Additional Services', 'Additional consultation topics.');

INSERT INTO services (id, category_id, title, slug, excerpt, intro, overview, who_can_apply, eligibility, requirements, documents, process, important_info, icon, price_from, price_to, sort_order, status, featured, seo_title, seo_description) VALUES
(1, 1, 'Study Permit', 'study-permit', 'Guidance for international students applying to study at a designated Canadian institution.',
'<p>Canada remains a leading destination for international education. A study permit is typically required for programs longer than six months at a designated learning institution.</p>',
'<p>We help applicants compare program options, prepare a complete file, and understand how studies can connect to later work and residence pathways.</p>',
'<p>Prospective students who hold a letter of acceptance from a designated learning institution and can show funds, ties, and a genuine study plan.</p>',
'<ul><li>Letter of acceptance from a DLI</li><li>Proof of funds for tuition and living costs</li><li>Intention to leave at the end of authorized stay unless another status is granted</li></ul>',
'<ul><li>Choose a program that matches academic history and future goals</li><li>Prepare a clear study plan</li><li>Complete medical and police documents when requested</li></ul>',
'<ul><li>Valid passport</li><li>Letter of acceptance</li><li>Financial evidence</li><li>Academic records</li><li>Language scores when required</li></ul>',
'<ol><li>Program and school selection</li><li>Document checklist</li><li>Application review</li><li>Submission and follow-up</li></ol>',
'<p>Short programs under six months may not require a study permit. Always confirm current IRCC rules before applying.</p>',
'bi-mortarboard', '150', '1500', 1, 1, 1, 'Study Permit Canada | Four Seasons Canada', 'Original guidance for Canadian study permit applications.'),
(2, 1, 'Post Graduation Work Permit', 'post-graduation-work-permit', 'Open work permit options after completing an eligible Canadian program.',
'<p>Graduates of eligible Canadian post-secondary programs may apply for a post-graduation work permit to gain Canadian work experience.</p>',
'<p>PGWP length depends on program duration and current government rules. Work experience obtained afterward may support some permanent residence programs.</p>',
'<p>Students who completed an eligible program at a designated institution and apply within the required timeframe.</p>',
'<ul><li>Eligible program completion</li><li>Valid status or restoration if applicable</li><li>Application within IRCC deadlines</li></ul>',
'<ul><li>Confirm program eligibility before enrolment</li><li>Keep study status valid through completion</li></ul>',
'<ul><li>Completion letter or transcript</li><li>Passport</li><li>Previous permits</li></ul>',
'<ol><li>Eligibility review</li><li>Document assembly</li><li>Application filing</li></ol>',
'<p>Co-op or internship time during studies usually does not count toward some later experience-class programs.</p>',
'bi-briefcase', '200', '300', 2, 1, 1, 'Post Graduation Work Permit | Four Seasons Canada', 'Support for PGWP applications after Canadian studies.'),
(3, 1, 'Spouse Open Work Permit', 'spouse-open-work-permit', 'Open work options for eligible spouses of students or workers in Canada.',
'<p>Eligible spouses or common-law partners of some students and workers may apply for an open work permit, subject to current program rules.</p>',
'<p>An open work permit can allow the spouse to work for most employers in Canada while the principal applicant studies or works.</p>',
'<p>Spouses of eligible international students or foreign workers who meet relationship and status requirements.</p>',
'<ul><li>Valid relationship evidence</li><li>Principal applicant holds eligible status</li><li>Sufficient funds and admissibility</li></ul>',
'<ul><li>Confirm the principal applicant’s program or occupation remains eligible</li></ul>',
'<ul><li>Marriage or partnership documents</li><li>Passports</li><li>Study or work permit copies</li></ul>',
'<ol><li>Eligibility screening</li><li>File preparation</li><li>Submission</li></ol>',
'<p>Rules for spouse work permits change. We review the latest criteria for each case.</p>',
'bi-people', '0', '0', 3, 1, 1, 'Spouse Open Work Permit | Four Seasons Canada', 'Guidance for eligible accompanying spouses.'),
(4, 1, 'Status Extension', 'status-extension', 'Help extending study, work, or visitor status before it expires.',
'<p>People already in Canada can often apply to extend their status before the current permit expires.</p>',
'<p>Timely extensions help avoid loss of status. Restoration may be possible in limited circumstances if status has already lapsed.</p>',
'<p>Temporary residents who need more time to study, work, or visit.</p>',
'<ul><li>Apply before expiry whenever possible</li><li>Maintain copies of all permits</li></ul>',
'<ul><li>Updated financial proof</li><li>Updated school or employer letters as applicable</li></ul>',
'<ul><li>Current permit</li><li>Passport</li><li>Supporting letters</li></ul>',
'<ol><li>Deadline check</li><li>Document update</li><li>Online filing</li></ol>',
'<p>Do not wait until the last day. Processing times vary.</p>',
'bi-clock-history', '200', '200', 4, 1, 1, 'Status Extension Canada | Four Seasons Canada', 'Extend study, work, or visitor status in Canada.'),
(5, 1, 'School Admission', 'school-admission', 'Help selecting Canadian institutions and preparing admission files.',
'<p>Choosing the right school and program is the first step toward a study permit and later career options.</p>',
'<p>We discuss academic background, budget, location, and post-graduation work eligibility before recommending options.</p>',
'<p>Students seeking college, university, or pathway programs in Canada.</p>',
'<ul><li>Academic transcripts</li><li>Language test results when required</li></ul>',
'<ul><li>Match program length and credential type to goals</li></ul>',
'<ul><li>Transcripts</li><li>Passport bio page</li><li>Resume</li></ul>',
'<ol><li>Consultation</li><li>School shortlist</li><li>Application support</li></ol>',
'<p>Admission offers do not guarantee a study permit.</p>',
'bi-building', '0', '0', 5, 1, 0, 'School Admission Canada | Four Seasons Canada', 'Canadian school admission guidance.'),
(6, 2, 'Express Entry', 'express-entry', 'Federal skilled immigration managed through the Express Entry system.',
'<p>Express Entry manages applications for several federal economic programs using a points-based ranking system.</p>',
'<p>Candidates create a profile, receive a Comprehensive Ranking System score, and may receive an invitation to apply for permanent residence.</p>',
'<p>Skilled workers who meet language, experience, and education thresholds for an eligible program.</p>',
'<ul><li>Language test results</li><li>Educational credential assessment when required</li><li>Skilled work experience</li></ul>',
'<ul><li>Keep documents current</li><li>Update the profile after new scores or experience</li></ul>',
'<ul><li>Passport</li><li>Language results</li><li>ECA</li><li>Employment letters</li></ul>',
'<ol><li>Eligibility assessment</li><li>Profile creation</li><li>Invitation response</li></ol>',
'<p>An Express Entry profile is not a permanent residence application.</p>',
'bi-graph-up', '0', '0', 1, 1, 1, 'Express Entry | Four Seasons Canada', 'Express Entry consulting for skilled immigration.'),
(7, 2, 'Canadian Experience Class', 'canadian-experience-class', 'Permanent residence for people with eligible Canadian skilled work experience.',
'<p>Canadian Experience Class is designed for temporary workers and graduates who have already gained skilled Canadian work experience.</p>',
'<p>It is managed through Express Entry and generally requires at least one year of eligible full-time (or equivalent) skilled work in Canada.</p>',
'<p>Workers and graduates who obtained experience on a valid work permit after studies.</p>',
'<ul><li>One year of skilled Canadian work</li><li>Language ability at the required level</li><li>Plan to live outside Quebec</li></ul>',
'<ul><li>Experience during full-time studies usually does not count</li></ul>',
'<ul><li>T4s and pay stubs</li><li>Employer letters</li><li>Language tests</li></ul>',
'<ol><li>NOC review</li><li>Profile</li><li>ITA filing</li></ol>',
'<p>Job duties must match the selected occupation description.</p>',
'bi-award', '0', '0', 2, 1, 1, 'Canadian Experience Class | Four Seasons Canada', 'CEC pathway guidance.'),
(8, 2, 'Federal Skilled Worker', 'federal-skilled-worker', 'Points-based skilled worker program for applicants inside or outside Canada.',
'<p>The Federal Skilled Worker Program selects candidates based on age, education, language, experience, and adaptability.</p>',
'<p>Applicants do not need a Canadian job offer in every case, but they must meet minimum points and program criteria.</p>',
'<p>Skilled workers worldwide who meet the pass mark and language/education thresholds.</p>',
'<ul><li>At least one year of skilled experience</li><li>Language proficiency</li><li>Educational credential assessment</li></ul>',
'<ul><li>Accurate occupation matching</li></ul>',
'<ul><li>Reference letters</li><li>ECA</li><li>Language results</li></ul>',
'<ol><li>Points estimate</li><li>Document plan</li><li>Express Entry profile</li></ol>',
'<p>Settlement funds may be required if you do not have arranged employment.</p>',
'bi-globe', '0', '0', 3, 1, 1, 'Federal Skilled Worker | Four Seasons Canada', 'FSWP consulting and file preparation.'),
(9, 2, 'Provincial Nominee Programs', 'provincial-nominee-programs', 'Province-specific nomination streams that can support permanent residence.',
'<p>Provinces and territories operate nominee programs aligned with local labour needs.</p>',
'<p>A nomination can add significant points in Express Entry or provide a paper-based PR pathway, depending on the stream.</p>',
'<p>Workers, graduates, or entrepreneurs who meet a specific provincial stream.</p>',
'<ul><li>Connection to the province when required</li><li>Occupation in demand</li><li>Language and work criteria of the stream</li></ul>',
'<ul><li>Do not apply to a stream that does not match your occupation or location</li></ul>',
'<ul><li>Job offer if required</li><li>Education and language proof</li></ul>',
'<ol><li>Stream matching</li><li>Provincial filing</li><li>Federal PR stage</li></ol>',
'<p>Each province publishes its own intake rules and pauses.</p>',
'bi-geo-alt', '0', '0', 4, 1, 1, 'Provincial Nominee Programs | Four Seasons Canada', 'PNP stream matching and applications.'),
(10, 2, 'Pilot Programs', 'pilot-programs', 'Targeted federal or regional pilots for communities and occupations.',
'<p>Canada periodically launches pilots to attract workers to specific regions, industries, or communities.</p>',
'<p>Examples have included rural, northern, and caregiver-related initiatives. Criteria are stream-specific and can close with little notice.</p>',
'<p>Applicants who meet a current pilot’s occupation, job-offer, or community requirements.</p>',
'<ul><li>Confirm the pilot is still accepting applications</li></ul>',
'<ul><li>Employer or community support when required</li></ul>',
'<ul><li>Job offer</li><li>Language results</li></ul>',
'<ol><li>Pilot identification</li><li>Eligibility check</li><li>Application</li></ol>',
'<p>Pilots change often. We verify official sources before proceeding.</p>',
'bi-flag', '0', '0', 5, 1, 1, 'Immigration Pilot Programs | Four Seasons Canada', 'Guidance on current Canadian immigration pilots.'),
(11, 3, 'Family Sponsorship', 'family-sponsorship', 'Sponsor a spouse, partner, or dependent child to live in Canada.',
'<p>Canadian citizens and permanent residents may sponsor certain family members when they meet income and relationship requirements.</p>',
'<p>Spousal and partner sponsorship is one of the most common family class applications.</p>',
'<p>Eligible sponsors in Canada (or citizens abroad who intend to return) and their qualifying family members.</p>',
'<ul><li>Sponsor status as citizen or PR</li><li>Genuine relationship</li><li>Undertaking of support</li></ul>',
'<ul><li>Complete relationship evidence</li></ul>',
'<ul><li>Identity documents</li><li>Relationship proof</li><li>Police and medicals when requested</li></ul>',
'<ol><li>Sponsor eligibility</li><li>Package assembly</li><li>Filing and updates</li></ol>',
'<p>Misrepresentation can lead to refusal and bars. Honesty in the file is essential.</p>',
'bi-heart', '0', '0', 1, 1, 1, 'Family Sponsorship | Four Seasons Canada', 'Spouse and child sponsorship consulting.'),
(12, 3, 'Parents and Grandparents', 'parents-and-grandparents', 'Options for parents and grandparents, including sponsorship intakes when open.',
'<p>The Parents and Grandparents Program opens in limited intakes. Super Visa can be an alternative for longer visits.</p>',
'<p>Sponsors must meet income cut-offs for a required number of years when the program is running.</p>',
'<p>Citizens and PRs who meet income and residency rules, and their parents or grandparents.</p>',
'<ul><li>Minimum necessary income</li><li>Interest to sponsor when IRCC opens a window</li></ul>',
'<ul><li>Keep tax filings in order</li></ul>',
'<ul><li>NOAs</li><li>Identity documents</li></ul>',
'<ol><li>Income review</li><li>Intake strategy</li><li>Application when invited</li></ol>',
'<p>Intake methods change. We monitor official announcements.</p>',
'bi-house-heart', '0', '0', 2, 1, 1, 'Parents and Grandparents | Four Seasons Canada', 'PGP and related family options.'),
(13, 3, 'Other Relatives', 'other-relatives', 'Limited options to sponsor other relatives in specific situations.',
'<p>Sponsorship of other relatives is narrowly defined. Most applicants will not qualify unless they meet orphan, lone-relative, or similar rules.</p>',
'<p>We explain whether a relative falls into an eligible category before any filing.</p>',
'<p>Sponsors with no closer family and a qualifying relative, or other rare categories.</p>',
'<ul><li>Confirm the relationship category in current regulations</li></ul>',
'<ul><li>Do not assume cousins or siblings are always eligible</li></ul>',
'<ul><li>Civil documents proving relationship</li></ul>',
'<ol><li>Category review</li><li>Go or no-go advice</li><li>Filing if eligible</li></ol>',
'<p>If sponsorship is not available, other temporary or economic pathways may be discussed.</p>',
'bi-diagram-3', '0', '0', 3, 1, 1, 'Other Relatives Sponsorship | Four Seasons Canada', 'Advice on limited other-relative sponsorship.'),
(14, 4, 'Family or Leisure', 'family-or-leisure', 'Visitor visa support for family visits and tourism.',
'<p>Many travellers need a visitor visa (TRV) unless they are visa-exempt and travel with an eTA.</p>',
'<p>Officers look at purpose of travel, funds, ties to the home country, and travel history.</p>',
'<p>People visiting family or taking a holiday in Canada.</p>',
'<ul><li>Valid passport</li><li>Purpose of visit</li><li>Funds and ties</li></ul>',
'<ul><li>Invitation letters should be truthful and complete</li></ul>',
'<ul><li>Bank records</li><li>Employment letter</li><li>Itinerary</li></ul>',
'<ol><li>Purpose letter</li><li>Document list</li><li>Application</li></ol>',
'<p>A visitor visa does not authorize work or long-term study.</p>',
'bi-airplane', '0', '0', 1, 1, 1, 'Visitor Visa Canada | Four Seasons Canada', 'Family and leisure visitor visa guidance.'),
(15, 4, 'Super Visa', 'super-visa', 'Longer-stay visa option for parents and grandparents of citizens or PRs.',
'<p>A Super Visa can allow eligible parents and grandparents to stay for extended periods, subject to insurance and income rules.</p>',
'<p>Private medical insurance meeting IRCC conditions is required.</p>',
'<p>Parents and grandparents of Canadian citizens or permanent residents.</p>',
'<ul><li>Invitation from a child or grandchild in Canada</li><li>Meeting low-income cut-off</li><li>Qualifying insurance</li></ul>',
'<ul><li>Insurance must remain valid as required</li></ul>',
'<ul><li>Insurance policy</li><li>NOAs of host</li><li>Relationship proof</li></ul>',
'<ol><li>Host eligibility</li><li>Insurance</li><li>Visa filing</li></ol>',
'<p>Super Visa holders still cannot work in Canada.</p>',
'bi-passport', '0', '0', 2, 1, 1, 'Super Visa Canada | Four Seasons Canada', 'Parent and grandparent Super Visa support.'),
(16, 4, 'Business or Exploratory', 'business-or-exploratory', 'Business visitor guidance for meetings, conferences, and exploratory trips.',
'<p>Business visitors may attend meetings or explore opportunities without entering the Canadian labour market.</p>',
'<p>If the activity looks like work for a Canadian employer, a work permit may be required instead.</p>',
'<p>Entrepreneurs, employees of foreign companies, and conference attendees.</p>',
'<ul><li>Clear business purpose</li><li>Ties and funds</li><li>No hands-on work for a Canadian business unless authorized</li></ul>',
'<ul><li>Distinguish visitor activity from work</li></ul>',
'<ul><li>Invitation</li><li>Company letter</li><li>Itinerary</li></ul>',
'<ol><li>Activity review</li><li>Letter drafting support</li><li>Filing</li></ol>',
'<p>Misclassified work can lead to refusal at the border.</p>',
'bi-briefcase-fill', '0', '0', 3, 1, 1, 'Business Visitor Canada | Four Seasons Canada', 'Business and exploratory visit consulting.'),
(17, 5, 'Citizenship', 'citizenship', 'Help preparing a Canadian citizenship application when residence requirements are met.',
'<p>Permanent residents who meet physical presence, tax, and language/knowledge requirements may apply for citizenship.</p>',
'<p>We calculate presence days and review supporting travel history.</p>',
'<p>Permanent residents who believe they meet current presence rules.</p>',
'<ul><li>Required days in Canada</li><li>Tax filings</li><li>Language evidence if applicable</li></ul>',
'<ul><li>Keep travel dates accurate</li></ul>',
'<ul><li>PR card</li><li>Passport stamps and tickets</li><li>Language proof</li></ul>',
'<ol><li>Presence calculator</li><li>Package</li><li>Submission</li></ol>',
'<p>Incomplete travel history is a common delay.</p>',
'bi-bookmark-star', '0', '0', 1, 1, 1, 'Canadian Citizenship | Four Seasons Canada', 'Citizenship application support.'),
(18, 5, 'PR Renewal', 'pr-renewal', 'Permanent resident card renewal and travel document advice.',
'<p>PR cards expire and should be renewed before travel. Presence rules still apply for maintaining status.</p>',
'<p>We review residency obligation concerns before filing.</p>',
'<p>Permanent residents whose card is expired or expiring.</p>',
'<ul><li>Residency obligation of two years in five in most cases</li></ul>',
'<ul><li>Humanitarian exceptions are case-specific</li></ul>',
'<ul><li>Old PR card</li><li>Travel history</li><li>Photos</li></ul>',
'<ol><li>Residency review</li><li>Forms</li><li>Filing</li></ol>',
'<p>A PR card is a travel document, not the source of status itself.</p>',
'bi-credit-card', '0', '0', 2, 1, 1, 'PR Card Renewal | Four Seasons Canada', 'PR card renewal assistance.'),
(19, 5, 'Status Restoration', 'status-restoration', 'Possible restoration of visitor, student, or worker status after expiry.',
'<p>If status expired recently, restoration may be available within a limited period, together with a new permit application.</p>',
'<p>Restoration is discretionary. It is better to extend before expiry.</p>',
'<p>People who lost temporary status and are still in Canada within restoration timelines.</p>',
'<ul><li>Apply within the restoration window</li><li>Remain in Canada while waiting</li></ul>',
'<ul><li>Do not work or study unless authorized</li></ul>',
'<ul><li>Expired permit</li><li>Explanation letter</li><li>New permit documents</li></ul>',
'<ol><li>Timeline check</li><li>Restoration + new status package</li></ol>',
'<p>Leaving Canada may affect restoration strategy.</p>',
'bi-arrow-counterclockwise', '0', '0', 3, 1, 1, 'Status Restoration | Four Seasons Canada', 'Restore expired temporary status when eligible.'),
(20, 5, 'LMIA', 'lmia', 'Labour Market Impact Assessment support for employers and workers.',
'<p>Many employer-specific work permits require a positive LMIA from ESDC unless an exemption applies.</p>',
'<p>Employers must usually advertise and show that hiring a foreign worker is justified.</p>',
'<p>Canadian employers and foreign nationals in LMIA-based streams.</p>',
'<ul><li>Genuine job offer</li><li>Wage and advertisement rules</li></ul>',
'<ul><li>Keep recruitment records</li></ul>',
'<ul><li>Job contract</li><li>Business documents</li><li>Ads</li></ul>',
'<ol><li>Stream selection</li><li>Recruitment</li><li>LMIA filing</li></ol>',
'<p>LMIA and work permit are separate applications.</p>',
'bi-file-earmark-text', '0', '0', 4, 1, 1, 'LMIA Canada | Four Seasons Canada', 'LMIA process overview and file support.'),
(21, 5, 'Work Permit', 'work-permit', 'Employer-specific and open work permit orientation.',
'<p>Work permits may be open or employer-specific depending on the stream, including IEC, LMIA-based, and some accompanying-family categories.</p>',
'<p>We identify the correct stream before collecting documents.</p>',
'<p>Foreign nationals with a job offer or an open-permit category.</p>',
'<ul><li>Job offer or open-permit eligibility</li><li>Medicals when required</li></ul>',
'<ul><li>Do not start work before authorization</li></ul>',
'<ul><li>Contract</li><li>LMIA if needed</li><li>Passport</li></ul>',
'<ol><li>Stream review</li><li>File</li><li>Filing</li></ol>',
'<p>Working without authorization can harm future applications.</p>',
'bi-person-badge', '0', '0', 5, 1, 1, 'Work Permit Canada | Four Seasons Canada', 'Canadian work permit consulting.'),
(22, 5, 'Visa Refusals', 'visa-refusals', 'Review of refused applications and options to re-apply or seek other remedies.',
'<p>A refusal is not always the end of the process. We review officer notes where available and identify weak points.</p>',
'<p>Options may include a stronger re-application, restoration, or other legal routes depending on the case.</p>',
'<p>Applicants who received a refusal letter.</p>',
'<ul><li>Refusal letter and full previous file</li></ul>',
'<ul><li>Do not resubmit the same package unchanged</li></ul>',
'<ul><li>GCMS notes if obtained</li><li>Previous forms</li></ul>',
'<ol><li>Refusal analysis</li><li>Strategy</li><li>New filing if appropriate</li></ol>',
'<p>Deadlines for some remedies are short. Contact us promptly.</p>',
'bi-x-octagon', '0', '0', 6, 1, 1, 'Visa Refusal Assistance | Four Seasons Canada', 'Help after a Canadian visa refusal.'),
(23, 6, 'Caregiver Program', 'caregiver-program', 'Information on caregiver-related work and residence pilots when available.',
'<p>Caregiver pathways have changed over the years. Current options depend on active federal pilots and work permit rules.</p>',
'<p>We confirm whether a job offer and occupation match an open stream before recommending action.</p>',
'<p>Caregivers with qualifying job offers and language/education levels of the current program.</p>',
'<ul><li>Valid job offer in a qualifying occupation</li></ul>',
'<ul><li>Verify the program is open</li></ul>',
'<ul><li>Contract</li><li>Language test</li><li>Education</li></ul>',
'<ol><li>Program check</li><li>Work permit or PR stage as applicable</li></ol>',
'<p>Historical live-in caregiver rules no longer apply in the same form.</p>',
'bi-heart-pulse', '0', '0', 1, 1, 0, 'Caregiver Program | Four Seasons Canada', 'Caregiver pathway orientation.');

INSERT INTO service_faqs (service_id, question, answer, sort_order) VALUES
(1, 'Do I always need a study permit?', 'Programs of six months or less often do not require a study permit, but longer programs usually do. We confirm the latest IRCC instructions for your program.', 1),
(1, 'Can I work while studying?', 'Many full-time students at eligible institutions can work limited hours, subject to current rules printed on the permit and IRCC updates.', 2),
(6, 'Is Express Entry a visa by itself?', 'No. It is a system that manages profiles for certain economic programs. You still need an invitation and a full permanent residence application.', 1),
(14, 'How long can I stay as a visitor?', 'Authorized stay is decided by the officer, often up to six months. Always check the stamp or visitor record.', 1);

INSERT INTO service_packages (service_id, title, price, description, features, sort_order) VALUES
(1, 'Ask Anything', '$150', '1 hour file review and consultation', "Consultation|Assessment notes|Personalized checklist|Phone or online support", 1),
(1, 'Hassle Free', '$1500', 'Full package for one applicant', "Authorized representation|Forms and file review|Study plan assistance|Ongoing support", 2);

INSERT INTO schools (id, name, slug, location, province, city, description, website, featured, status) VALUES
(1, 'Niagara College', 'niagara-college', 'Welland, Ontario', 'Ontario', 'Welland', 'Public college known for hospitality, health, business, and technology programs.', 'https://www.niagaracollege.ca', 1, 1),
(2, 'Fanshawe College', 'fanshawe-college', 'London, Ontario', 'Ontario', 'London', 'Applied programs across aviation, health, IT, and business.', 'https://www.fanshawec.ca', 1, 1),
(3, 'Humber College', 'humber-college', 'Etobicoke, Ontario', 'Ontario', 'Etobicoke', 'Large college with degree, diploma, and postgraduate credentials.', 'https://humber.ca', 1, 1),
(4, 'Centennial College', 'centennial-college', 'Toronto, Ontario', 'Ontario', 'Toronto', 'Toronto college with strengths in hospitality, business, and applied arts.', 'https://www.centennialcollege.ca', 1, 1),
(5, 'Seneca College', 'seneca-college', 'North York, Ontario', 'Ontario', 'North York', 'Programs in business, media, aviation-related studies, and technology.', 'https://www.senecacollege.ca', 1, 1),
(6, 'George Brown College', 'george-brown-college', 'Toronto, Ontario', 'Ontario', 'Toronto', 'Downtown Toronto college recognized for culinary and community programs.', 'https://www.georgebrown.ca', 1, 1),
(7, 'Vancouver Community College', 'vancouver-community-college', 'Vancouver, British Columbia', 'British Columbia', 'Vancouver', 'Urban college offering hospitality, culinary, and business credentials.', 'https://www.vcc.ca', 1, 1),
(8, 'University of Canada West', 'university-of-canada-west', 'Vancouver, British Columbia', 'British Columbia', 'Vancouver', 'Business-focused university offering undergraduate and MBA pathways.', 'https://www.ucanwest.ca', 1, 1),
(9, 'NAIT', 'nait', 'Edmonton, Alberta', 'Alberta', 'Edmonton', 'Polytechnic institute with technology, health, and trades programs.', 'https://www.nait.ca', 1, 1),
(10, 'SAIT', 'sait', 'Calgary, Alberta', 'Alberta', 'Calgary', 'Applied education in engineering technology, hospitality, and business.', 'https://www.sait.ca', 1, 1),
(11, 'Red River College Polytechnic', 'red-river-college', 'Winnipeg, Manitoba', 'Manitoba', 'Winnipeg', 'Applied programs in IT, business, and engineering technology.', 'https://www.rrc.ca', 1, 1),
(12, 'Saskatchewan Polytechnic', 'saskatchewan-polytechnic', 'Saskatoon, Saskatchewan', 'Saskatchewan', 'Saskatoon', 'Province-wide polytechnic with trades, health, and business programs.', 'https://saskpolytech.ca', 1, 1);

INSERT INTO school_programs (school_id, title, description) VALUES
(1, 'Hospitality and Tourism', 'Diploma options connected to hotels, tourism, and culinary pathways.'),
(1, 'Nursing and PSW', 'Health-related programs with competitive admission.'),
(2, 'Aviation and Technology', 'Applied technical programs including aviation-related streams.'),
(3, 'Business Degrees', 'Four-year and postgraduate business credentials.'),
(7, 'Hospitality Management', 'Diploma-level hospitality training in Vancouver.'),
(9, 'Engineering Technology', 'Hands-on technology diplomas.');

INSERT INTO team_members (full_name, slug, position, biography, email, sort_order, status) VALUES
('Leah Fe Balucan', 'leah-fe-balucan', 'Immigration Consultant', 'Regulated consultant focused on clear client communication and structured files.', 'info@four-seasons.ca', 1, 1),
('Kathleen Caldino', 'kathleen-caldino', 'Documentation Head', 'Coordinates document quality and checklist completeness across files.', 'info@four-seasons.ca', 2, 1),
('Fatima Balbuena', 'fatima-balbuena', 'Documentation Officer', 'Supports clients through document collection and application updates.', 'info@four-seasons.ca', 3, 1),
('Gelvin Rodriguez', 'gelvin-rodriguez', 'Documentation Officer', 'Helps applicants stay organized from first checklist to submission.', 'info@four-seasons.ca', 4, 1),
('Janine Tumulak', 'janine-tumulak', 'Documentation Officer', 'Provides patient, detail-oriented support throughout the process.', 'info@four-seasons.ca', 5, 1);

INSERT INTO events (title, slug, description, event_date, start_time, end_time, location, season, registration_info, featured, status, seo_title) VALUES
('Canada Immigration Workshop', 'canada-immigration-workshop', '<p>In-person briefing covering study and immigration options, with time for questions.</p>', '2026-06-20', '08:00:00', '17:00:00', 'Makati City', 'Summer', 'Register through the inquiry form and mention this event.', 1, 'published', 'Canada Immigration Workshop'),
('Online Coffee Briefing', 'online-coffee-briefing', '<p>Short virtual session introducing Canadian colleges and visa timelines.</p>', '2026-11-06', '20:00:00', '22:00:00', 'Online', 'Fall', 'Free registration via the website form.', 1, 'published', 'Online Coffee Briefing'),
('Campus Fair Preview', 'campus-fair-preview', '<p>Meet counsellors to compare Ontario and British Columbia institutions.</p>', '2026-10-23', '13:00:00', '17:00:00', 'Mississauga, Ontario', 'Fall', 'Walk-in or pre-register.', 0, 'published', 'Campus Fair Preview');

INSERT INTO blog_categories (id, title, slug) VALUES (1, 'News', 'news'), (2, 'Education', 'education'), (3, 'Immigration', 'immigration');

INSERT INTO blog_posts (category_id, title, slug, excerpt, body, author, status, published_at, seo_title, seo_description) VALUES
(1, 'Connecting Schools, Connecting Lives', 'connecting-schools-connecting-lives',
'Education fairs remain a practical way for families to compare Canadian programs in one place.',
'<p>Education fairs bring school representatives and families into the same room so questions about programs, intakes, and admissions can be answered directly.</p><p>Attendees should arrive with transcripts, a budget range, and a short list of career interests. That preparation makes counselling time more useful.</p>',
'Four Seasons Team', 'published', '2026-09-08 10:00:00', 'Connecting Schools, Connecting Lives', 'How education fairs help families compare Canadian study options.'),
(2, 'Planning a Canadian Study Timeline', 'planning-a-canadian-study-timeline',
'Most successful files start 8–12 months before the intended intake.',
'<p>Language testing, school applications, and visa processing all take time. Starting early reduces last-minute refusals caused by incomplete funds or late medicals.</p>',
'Four Seasons Team', 'published', '2026-08-01 10:00:00', 'Planning a Canadian Study Timeline', 'Suggested timeline for school and study permit applications.'),
(3, 'What Express Entry Actually Measures', 'what-express-entry-actually-measures',
'Language, age, education, and skilled experience still drive ranking.',
'<p>Express Entry rewards documented skilled work and official language results. Informal job titles that do not match duties can weaken a file.</p>',
'Four Seasons Team', 'published', '2026-07-12 10:00:00', 'What Express Entry Actually Measures', 'A plain-language look at CRS factors.');

INSERT INTO testimonials (client_name, service_label, quote, sort_order, status) VALUES
('Joy D.', 'Student visa with accompanying spouse', 'The team kept our checklist realistic and explained each request before we submitted.', 1, 1),
('Re-Ann L.', 'Study permit', 'Communication was consistent from school choice through visa filing.', 2, 1),
('Richard V.', 'Study permit', 'Clear advice and timely follow-up made a complicated process manageable.', 3, 1),
('Barbara G.', 'Student visa and work permit', 'They treated our family file as one plan instead of two disconnected applications.', 4, 1);

INSERT INTO faqs (question, answer, sort_order, status) VALUES
('Do I need an account to inquire?', 'No. Visitors submit a form. Our team contacts you directly.', 1, 1),
('Are you a government office?', 'No. We are a private consultancy. Decisions are made by Canadian authorities.', 2, 1);

INSERT INTO gallery_items (title, image, sort_order, status) VALUES
('Consultation', 'assets/images/gallery-1.svg', 1, 1),
('Workshop', 'assets/images/gallery-2.svg', 2, 1),
('Campus', 'assets/images/gallery-3.svg', 3, 1),
('Team', 'assets/images/gallery-4.svg', 4, 1),
('Fair', 'assets/images/gallery-5.svg', 5, 1),
('Office', 'assets/images/gallery-6.svg', 6, 1);

INSERT INTO pages (title, slug, body, seo_title, seo_description, status) VALUES
('Who We Are', 'who-we-are',
'<p>Four Seasons Canada is an immigration and international education consultancy. We help clients understand options, assemble complete files, and stay informed through each stage.</p><p>Our work is guided by professional standards, transparent communication, and respect for official Canadian requirements.</p><h2>Mission</h2><p>Deliver ethical, clear, and practical support so clients can make informed decisions about studying, working, visiting, or settling in Canada.</p><h2>Vision</h2><p>Be a trusted advisory option for families pursuing Canadian education and immigration, measured by service quality rather than shortcuts.</p>',
'Who We Are | Four Seasons Canada', 'About Four Seasons Canada, our mission, and our vision.', 1),
('What We Do', 'what-we-do',
'<p>We provide consulting across education, economic immigration, family sponsorship, visitor services, and related status applications.</p><p>Services range from a focused consultation to full representation, depending on what the client needs and what the case requires.</p>',
'What We Do | Four Seasons Canada', 'Overview of consultancy services.', 1),
('Where We Are', 'where-we-are',
'<p>Head office: 90 Burnhamthorpe Rd West, 14th Floor, Sussex Centre, Mississauga, Ontario L5B 3C3.</p><p>Appointments can be booked for phone, video, or in-person meetings during business hours.</p>',
'Where We Are | Four Seasons Canada', 'Office location in Mississauga, Ontario.', 1),
('Privacy Policy', 'privacy-policy',
'<p>Inquiry forms collect contact details so our staff can respond. We do not sell personal information. Records are stored in our database for follow-up and compliance.</p><p>You may email us to request a correction of your contact details.</p>',
'Privacy Policy | Four Seasons Canada', 'How inquiry data is used.', 1);

INSERT INTO homepage_sections (section_key, title, content_json, sort_order, status, updated_at) VALUES
('hero', 'Turning Visa Dreams Into New Beginnings', '{"headline":"Turning Visa Dreams Into New Beginnings!","subhead":"Your Future Abroad Starts With Us!","cta":"CONTACT ME","event_title":"Get to know Canada''s universities","event_cta":"REGISTER NOW"}', 1, 1, NOW()),
('did_you_know', 'Did You Know', '{"headline":"DID YOU KNOW there are over 60 options to immigrate to Canada?","text":"We assess your eligibility across available pathways. Find out whether a Canadian option may fit your profile.","cta":"COMPLETE EVALUATION"}', 2, 1, NOW()),
('about_stats', 'Leading Immigration Expert', '{"heading":"Leading Immigration Expert","mission_title":"our mission","vision_title":"our vision"}', 3, 1, NOW()),
('promo', 'Promo', '{"headline":"Seasonal school intake briefing","text":"Ask about current college and university intakes and related visa timelines.","cta":"REQUEST RETURN-CALL"}', 9, 1, NOW());

INSERT INTO homepage_sections (section_key, title, content_json, sort_order, status) VALUES
('stats', 'Stats', '[{"value":"10+","label":"Years of Experience","note":"Established 2017 in Canada"},{"value":"RCIC","label":"Authorized Representative","note":"Regulated Canadian Immigration Consultant"},{"value":"10,000+","label":"Client Files Supported","note":"Students, workers, and families"},{"value":"100+","label":"Canadian Institutions","note":"Education-focused network"}]', 4, 1);
